module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#0052ff",
        "primary-fixed": "#dde1ff",
        "on-surface-variant": "#434656",
        "secondary-fixed-dim": "#c0c7d4",
        "secondary-fixed": "#dce3f0",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f1f1",
        "inverse-surface": "#2f3131",
        "primary-fixed-dim": "#b7c4ff",
        "tertiary-fixed-dim": "#c3c7cd",
        "background": "#f9f9f9",
        "tertiary-container": "#62666c",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-secondary-fixed": "#151c26",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#43474d",
        "inverse-primary": "#b7c4ff",
        "on-tertiary-fixed": "#181c21",
        "surface-container-low": "#f3f3f4",
        "outline-variant": "#c3c5d9",
        "on-secondary-container": "#5c636f",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#414752",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#0038b6",
        "secondary-container": "#dae0ee",
        "on-primary-container": "#dfe3ff",
        "surface-container": "#eeeeee",
        "primary": "#003ec7",
        "surface": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "secondary": "#585f6a",
        "on-tertiary-container": "#e1e4eb",
        "tertiary-fixed": "#dfe2e9",
        "on-background": "#1a1c1c",
        "surface-tint": "#004ced",
        "on-secondary": "#ffffff",
        "tertiary": "#4a4e54",
        "on-primary-fixed": "#001452",
        "surface-dim": "#dadada",
        "outline": "#737688"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px"
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "space-grotesk": ["Space Grotesk"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
